<Calculator>:
	orientation: "vertical"

    BoxLayout:
        Label:
            text: ""
            id: igual
            width: 100

    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Clear"
            height: 30
            on_press: app.root.limpar_resultado()
        Button:
            text: "="
            on_press: app.root.mostra_resultado()

    BoxLayout:
        GridLayout:
            cols: 4
            spacing: 3

            Digitos:
                text: "1"
            Digitos:
                text: "2"
            Digitos:
                text: "3"
            Digitos:
                text: "+"
                
            Digitos:
                text: "4"
            Digitos:
                text: "5"
            Digitos:
                text: "6"
            Digitos:
                text: "-"
                
            Digitos:
                text: "7"
            Digitos:
                text: "8"
            Digitos:
                text: "9"
            Digitos:
                text: "÷"
            
            Button
                text: ""
            Digitos:
                text: "0"
            Button:
                text: ""
            Digitos:
                text: "x"

<Digitos@Button>:
    on_press: app.root.pega_tecla(self.text)