<Calculator>:
	orientation: "vertical"

    BoxLayout:
        Label:
            text: ""
            id: igual
            width: 100

    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Clear"
            height: 30
            on_press: app.root.limpar_resultado()
        Button:
            text: "="
            on_press: app.root.mostra_resultado()

    BoxLayout:
        GridLayout:
            cols: 4
            spacing: 3

            Button:
                text: "1"
                on_press: app.root.pega_tecla('1')
            Button:
                text: "2"
                on_press: app.root.pega_tecla('2')
            Button:
                text: "3"
                on_press: app.root.pega_tecla('3')
            Button:
                text: "+"
                on_press: app.root.pega_tecla('+')
                
            Button:
                text: "4"
                on_press: app.root.pega_tecla('4')
            Button:
                text: "5"
                on_press: app.root.pega_tecla('5')
            Button:
                text: "6"
                on_press: app.root.pega_tecla('6')
            Button:
                text: "-"
                on_press: app.root.pega_tecla('-')
                
            Button:
                text: "7"
                on_press: app.root.pega_tecla('7')
            Button:
                text: "8"
                on_press: app.root.pega_tecla('8')
            Button:
                text: "9"
                on_press: app.root.pega_tecla('9')
            Button:
                text: "÷"
                on_press: app.root.pega_tecla('÷')
            
            Button:
                text: ""
            Button:
                text: "0"
                on_press: app.root.pega_tecla('0')
            Button:
                text: ""
            Button:
                text: "x"
            	on_press: app.root.pega_tecla('x')